POST  http://localhost:4000/api/user
Content-Type: application/json

{
    "email": "hung123@gmail.com",
    "password": "Hun",
    "fullName": "Hungg"
}

###
POST  http://localhost:4000/api/login
Content-Type: application/json

{
    "email": "hung123@gmail.com",
    "password": "Hun"
}

###
GET http://localhost:4000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGIzMDdlZjRhODMxZjY5YmNiNDE2OCIsInJvbGUiOiJ1c2VyIiwiZW1haWwiOiJNaW5oIiwiaWF0IjoxNjUzMjg5MjgwLCJleHAiOjE2NTMzNzU2ODB9.XIs2thlZiNpxY0XbyUJKbitFq6pLyyTzeqMLbNMl7I4

###
DELETE  http://localhost:4000/api/user/62847e8c71ad96fa48dcbd67
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODQ3ZThjNzFhZDk2ZmE0OGRjYmQ2NyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjUyODUwNTI5fQ.94u9y5_QnEr5AGV25tz6SqgZdVQFHU9fZOTkqt_3PUg

###
PUT http://localhost:4000/api/user/628afa61ad075e6a46d3cb4b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGE4ODU0ODk2NjlkOTk3YmQ1ZWY0MCIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiTWFuaCIsImlhdCI6MTY1MzI3NTI2NSwiZXhwIjoxNjUzMzYxNjY1fQ.kqj5wh5G6BaXpqjSmJRW8BeLKz16CXVP28S2jBqhz-0
{
    "email": "Ha",
    "name": "Ha"
}

###
POST  http://localhost:4000/api/alo
Content-Type: application/json

{
    "title": "a",
    "content": "a"
}

###
GET http://localhost:4000/api/user/
Authorization: Bearer eyJlhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGIzNzg5ODU4NTE2NzUwNGRjNTc0NyIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiUXVvYyIsImlhdCI6MTY1MzI5MDkxNywiZXhwIjoxNjUzMzc3MzE3fQ.nmtebfDjxO-2xRLUny-Dep6PBun9I2cG0jXUPnnkcYY

###
PUT http://localhost:4000/api/user/62847faa7dd04b76b0bc4897
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODQ3ZmFhN2RkMDRiNzZiMGJjNDg5NyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjUyODUwOTY0fQ.SwpcWnyD1-5FR-NssdJj8wNaESc-NPyc2iZgYMgSd0Q

{
     "email": "Ha",
    "name": "Ha"
}

###
POST http://localhost:4000/api/customer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGE4ODU0ODk2NjlkOTk3YmQ1ZWY0MCIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiTWFuaCIsImlhdCI6MTY1MzM0NjI4OCwiZXhwIjoxNjUzNDMyNjg4fQ.ElVEp5s5KDatYI6qQDZm75KHmenVkX_ZjLMdXpD_Vrk

{
   
    "phone": "0963353585683"  
}

###
GET http://localhost:4000/api/customer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGE4ODU0ODk2NjlkOTk3YmQ1ZWY0MCIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiTWFuaCIsImlhdCI6MTY1MzI5MjE3NywiZXhwIjoxNjUzMzc4NTc3fQ.Uicy2ViwjaXMruUaUkpNLR-PJSFbJzhsONOr6SLNS5k
###
delete http://localhost:4000/api/customer/6285cb987f3a626a4d7ec1df
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGE4ODU0ODk2NjlkOTk3YmQ1ZWY0MCIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiTWFuaCIsImlhdCI6MTY1MzI3OTI0OSwiZXhwIjoxNjUzMzY1NjQ5fQ.jj1KSk17pRdmngQxvboFdk-zukbkB0yo1S0cDtSXSAY
###
PUT http://localhost:4000/api/customer/6285cc876e54829216c3158a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGE4ODU0ODk2NjlkOTk3YmQ1ZWY0MCIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiTWFuaCIsImlhdCI6MTY1MzI3OTI0OSwiZXhwIjoxNjUzMzY1NjQ5fQ.jj1KSk17pRdmngQxvboFdk-zukbkB0yo1S0cDtSXSAY
Content-Type: application/json;

{
    "fullname": "Trafenf Van Do",
   
    "phone": "099888589988"
    
}